language: node_js
cache:
  directories:
    - node_modules
node_js:
 - "node"
before_script:
  - npm prune
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug
script:
  - npm run lint
  - npm run coverage
  - npm run build
after_success:
  - npm run coverage:codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug