// Generated by typings
// Source: typings/globals/chai-arrays/index.d.ts
declare function chaiArrays(chai: any, utils: any): void;
declare namespace chaiArrays {}
declare module 'chai-arrays' {
    export = chaiArrays;
}
